format_version: 10
pipelines:
  bean-counter-local:
    group: local
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-7777dc0:
        git: https://github.com/jenish-jain/bean_counter
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            artifacts:
            - external:
                id: push-to-cs
                store_id: google-cloud-storage
                configuration:
                  options:
                    Destination: 'builds/'
                    Source: build.json
            tasks:
            - exec:
                arguments:
                - hello
                - '>>'
                - hello.txt
                command: echo
                run_if: passed
            - exec:
                arguments:
                - build.json
                command: touch
                run_if: passed
            - exec:
                arguments:
                - check the artifacts now
                command: echo
                run_if: passed
    - fetch_artifacts:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          fetch:
            timeout: 0
            is_file: false
            artifacts:
            - external:
                id: push-to-cs
                store_id: google-cloud-storage
                configuration:
                  options:
                    Destination: 'new_builds/'
                    Source: "builds"
            tasks:
            - exec:
                arguments:
                - fetching artifacts
                command: echo
                run_if: passed
            - exec:
                arguments:
                - build.json
                command: cat
                run_if: passed